
import { AppProvider } from "@context/AppProviders";
import "./globals.css";
import Provider from "@components/Provider";
import { ErrorProvider } from "@context/ErrorContext";

export const metadata = {
  title: "Land Me | Book Properties just for you.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <AppProvider>
          <ErrorProvider>
            <Provider>
              <main >
                {children}
              </main>
            </Provider>
          </ErrorProvider>
        </AppProvider>
      </body>
    </html>
  );
}
